FROM cmelab/gpuhoomd4conda:latest

USER root

RUN conda activate base

WORKDIR /opt && chmod u+rwx .

# install in base conda env
RUN git clone https://github.com/cmelab/flowerMD && \
    cd flowerMD && \
    conda env update -n base -f environment-gpu.yml && \
    conda clean --all --yes -f

WORKDIR flowerMD

RUN python -m pip install --user -e .
